CONFIG = {

    # ===== 画面 =====
    "screen_w": 1280,
    "screen_h": 720,
    "fullscreen": False,
    "window_title": "Laser Balloon Game",

    # ===== ゲーム基本 =====
    "game_time_sec": 30,
    "spawn_interval": 0.8,
    "max_balloons": 12,

    # ===== 風船サイズ =====
    "balloon_radius_min": 30,
    "balloon_radius_max": 70,

    # ===== 風船速度 =====
    "balloon_speed_min": 100,
    "balloon_speed_max": 300,
    "balloon_hit_compensation_sec": 0.12,
    "balloon_hit_offset_y": 0,

    # ===== スポーン位置 =====
    "spawn_x_margin": 80,
    "spawn_y_min": 20,
    "spawn_y_max": 100,

    # ===== 出現率 =====
    "spawn_rate_normal": 0.75,
    "spawn_rate_bonus": 0.18,
    "spawn_rate_bomb": 0.07,

    # ===== 得点 =====
    "score_normal": 30,
    "score_bonus": 20,
    "score_bomb": 10,

    # ===== コンボ =====
    "combo_x2_count": 5,
    "combo_x3_count": 10,
    "combo_x2_multiplier": 2,
    "combo_x3_multiplier": 3,

    # ===== レーザー検出 =====
    "laser_threshold": 205,
    "laser_min_area": 0,
    "laser_max_area": 2,
    "laser_v_min": 180,
    "laser_r_min": 60,
    "laser_red_margin": 28,
    "laser_response_min": 10,
    "laser_brightness_gain": 1.15,
    "laser_red_response_gain": 1.0,
    "laser_local_bg_kernel": 7,
    "laser_peak_window_radius": 4,
    "laser_peak_relative_threshold": 0.45,
    "laser_screen_smoothing": 0.35,
    "laser_raw_response_gain": 0.75,
    "laser_column_bias_gain": 0.8,
    "laser_column_bias_kernel": 81,
    "laser_temporal_gain": 0.65,
    "laser_bg_alpha": 0.04,
    "laser_tracking_search_radius": 110,
    "laser_tracking_min_score_ratio": 0.45,
    "laser_tracking_relaxed_min": 3,
    "laser_ignore_left_px": 0,
    "laser_ignore_right_px": 0,
    "laser_ignore_top_px": 0,
    "laser_ignore_bottom_px": 0,
    "laser_screen_offset_x": 0,
    "laser_screen_offset_y": 18,
    "laser_hold_sec": 0.12,

    # ===== カメラ =====
    "camera_index": 0,
    "camera_backend": "dshow",
    "camera_probe_indices": [0, 1, 2, 3, 4, 5],
    "camera_buffer_size": 1,
    "camera_w": 1280,
    "camera_h": 720,
    "camera_auto_exposure": 0.25,
    "camera_exposure": -7,
    "camera_gain": 0,
    "camera_brightness": 20,
    "shot_frame_grabs": 2,
    "show_camera_window": False,
    "show_threshold_window": False,
    "show_tracking_window": True,
    "show_calibration_overlay": True,
    "tracking_window_scale": 0.6,

    # ===== シリアル =====
    "use_serial": True,
    "serial_port": "COM10",
    "baudrate": 115200,
    "shot_cooldown_sec": 0.15,

    # ===== ショット表示 =====
    "show_shot_marker": False,
    "shot_marker_duration_sec": 0.2,
    "camera_feedback_duration_sec": 0.8,
    "shot_marker_radius": 18,
    "shot_hit_color": (90, 255, 180),
    "shot_miss_color": (80, 200, 255),
    "enable_sound": True,
    "sound_volume": 0.75,
    "shot_sound_volume": 0.95,
    "shot_sound_duration_sec": 0.09,
    "pop_sound_volume": 1.0,
    "pop_sound_duration_sec": 0.22,
    "enable_bgm": True,
    "bgm_file": "Energy.mp3",
    "bgm_volume": 0.28,
    "bgm_step_sec": 0.22,
    "bgm_note_sec": 0.17,

    # ===== カーソル =====
    "show_projected_laser_cursor": False,
    "laser_cursor_color": (90, 220, 255),

    # ===== 風船色 =====
    "balloon_normal_color": (18, 70, 105),
    "balloon_bonus_color": (28, 110, 120),
    "balloon_bomb_color": (32, 42, 58),
    "balloon_string_color": (45, 58, 74),
    "balloon_normal_outline_color": (90, 175, 215),
    "balloon_bonus_outline_color": (120, 230, 240),
    "balloon_bomb_outline_color": (125, 140, 165),
    "balloon_outline_width": 1,

    # ===== 破裂エフェクト =====
    "pop_effect_duration_sec": 0.28,
    "pop_particle_count": 12,
    "pop_particle_speed_min": 140,
    "pop_particle_speed_max": 280,
    "pop_particle_gravity": 420,
    "pop_flash_color": (160, 220, 255),

    # ===== UI =====
    "bg_color": (7, 10, 18),
    "text_color": (115, 130, 145),
    "show_ui_text": True,
    "projector_dim_alpha": 120,
    "ui_panel_x": 16,
    "ui_panel_y": 16,
    "ui_panel_width": 220,
    "ui_panel_height": 118,
    "ui_panel_color": (6, 10, 16, 145),
    "ui_line_gap": 34,
    "ui_text_color": (108, 124, 138),
    "ui_shot_on_color": (118, 132, 145),
    "ui_shot_off_color": (78, 92, 104),
    "shot_status_duration_sec": 0.18,
    "action_button_width": 260,
    "action_button_height": 160,
    "action_button_color": (8, 12, 18, 185),
    "action_button_outline_color": (72, 88, 102),
    "action_icon_color": (128, 144, 156),
    "action_label_color": (112, 128, 140),
    "score_title_color": (52, 62, 72),
    "score_subtitle_color": (64, 76, 88),
    "score_value_color": (110, 124, 136),
    "name_title_color": (72, 84, 96),
    "name_subtitle_color": (84, 96, 108),
    "name_field_color": (8, 12, 18, 180),
    "name_field_outline_color": (66, 80, 92),
    "name_value_color": (116, 132, 144),
    "name_hint_color": (84, 96, 108),
    "name_key_color": (8, 12, 18, 170),
    "name_key_outline_color": (64, 78, 90),
    "name_key_text_color": (116, 130, 142),
    "name_action_color": (10, 15, 22, 185),
    "name_action_outline_color": (74, 88, 100),
    "name_action_text_color": (118, 132, 144),
    "ranking_title_color": (72, 84, 96),
    "ranking_subtitle_color": (84, 96, 108),
    "ranking_panel_color": (7, 11, 17, 180),
    "ranking_panel_outline_color": (60, 72, 84),
    "ranking_row_color": (8, 12, 18, 120),
    "ranking_row_outline_color": (50, 62, 74),
    "ranking_highlight_color": (12, 18, 26, 185),
    "ranking_highlight_outline_color": (92, 108, 122),
    "ranking_rank_color": (112, 126, 138),
    "ranking_name_color": (122, 138, 150),
    "ranking_score_color": (132, 146, 158),
    "ranking_empty_color": (86, 98, 110),
    "player_name_max_length": 6,
    "player_name_min_length_hint": 3,
    "name_keyboard_rows": ["ABCDEFG", "HIJKLMN", "OPQRSTU", "VWXYZ-"],
    "name_key_width": 92,
    "name_key_height": 68,
    "name_key_gap_x": 12,
    "name_key_gap_y": 12,
    "name_keyboard_y": 260,
    "name_action_width": 160,
    "name_action_height": 72,
    "name_action_gap": 18,
    "name_action_y": 610,
    "daily_ranking_file": "daily_rankings.json",
    "daily_ranking_limit": 10,
    "daily_ranking_display_count": 10,
    "ranking_board_height": 360,

    # ===== 投影補正 =====
    # カメラ画像上のスクリーン4点
    # 左上, 右上, 右下, 左下
    "cam_points_ref_w": 1280,
    "cam_points_ref_h": 720,
    "cam_point_step": 2,
    "cam_point_step_fast": 10,
    "auto_calibration_canny_low": 40,
    "auto_calibration_canny_high": 120,
    "auto_calibration_min_area_ratio": 0.12,
    "auto_calibration_epsilon_ratio": 0.03,
    "cam_points": [
        [202, 82],
        [1060, 110],
        [1040, 606],
        [202, 600],
    ],

}
